version: "3.3"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
  fpm:
    build:
      context: .
      dockerfile: docker/php-fpm.Dockerfile
    volumes:
      - ./:/var/www/laravel-news
    links:
      - mysql
  nginx:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    ports:
      - "8050:80"
    links:
      - fpm
  cache:
    image: redis:latest
    ports:
      - 6379:6379
    links:
      - mysql
